In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def arr(file):
    df = pd.DataFrame()
    df['Time'] = pd.date_range('2020-12-21 23:00:00', '2023-01-10 20:00:00', freq='H')
    
    temp = pd.read_excel(file)
    temp = temp[['time', 'E_min_min']]
    temp['time'] = pd.to_datetime(temp['time'], format = '%d.%m.%Y %H:%M')
    temp.columns = ['Time', 'E_min_min']
    
    df = df.merge(temp, on='Time', how='left').fillna(np.nan)
    
    arr = [np.nan]
    i = 1
    while i <= len(df)-1:
        if df.iloc[i-1]['E_min_min']==np.nan:
            arr.append(np.nan)
        elif df.iloc[i]['E_min_min']==np.nan:
            arr.append(np.nan)
        else:
            arr.append((df.iloc[i]['E_min_min']-df.iloc[i-1]['E_min_min']))
        i+=1
    df[file] = arr
    return df[['Time',file]]

## Consumption

In [3]:
cons_k28 = arr('Consumption_k28.xlsx')

In [4]:
cons_k24 = arr('Consumption_k24.xlsx')

In [5]:
cons_h16 = arr('Consumption_h16.xlsx')

In [6]:
cons_h22 = arr('Consumption_h22.xlsx')

In [7]:
cons_h28 = arr('Consumption_h28.xlsx')

In [8]:
cons_h32 = arr('Consumption_h32.xlsx')

## Production

In [9]:
prod_k24 = arr('Production_k24.xlsx')

In [10]:
prod_k28 = arr('Production_k28.xlsx')

In [11]:
prod_h16 = arr('Production_h16.xlsx')

In [12]:
prod_h22 = arr('Production_h22.xlsx')

In [13]:
prod_h28 = arr('Production_h28.xlsx')

In [14]:
prod_h32 = arr('Production_h32.xlsx')

## Combining dataframes

In [30]:
df = pd.DataFrame()
df['Time'] = pd.date_range('2020-12-21 23:00:00', '2023-01-10 20:00:00', freq='H')

lists = [prod_k24, prod_k28, prod_h16, prod_h22, prod_h28, prod_h32, cons_k24, cons_k28, cons_h16, cons_h22, cons_h28, cons_h32]


for l in lists:
    df = df.merge(l, on='Time')
    
df = df.set_index(df['Time']).drop(['Time'],axis=1)
df.columns = lists = ['prod_k24', 'prod_k28', 'prod_h16', 'prod_h22', 'prod_h28', 'prod_h32', 'cons_k24', 'cons_k28', 'cons_h16', 'cons_h22', 'cons_h28', 'cons_h32']
df = df.drop(df.index[0])
df.to_csv('complete_dataset.csv')

In [36]:
df

,prod_k24,prod_k28,prod_h16,prod_h22,prod_h28,prod_h32,cons_k24,cons_k28,cons_h16,cons_h22,cons_h28,cons_h32
Time,,,,,,,,,,,,
2020-12-22 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,3.1,5.0,3.1,6.3,4.9,6.6
2020-12-22 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,2.6,4.3,2.6,6.5,4.4,5.4
2020-12-22 02:00:00,0.0,0.0,0.0,0.1,0.1,0.0,2.2,4.0,2.2,4.3,3.9,4.4
2020-12-22 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,2.3,3.8,2.3,3.3,3.2,3.7
2020-12-22 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,1.9,3.1,1.9,3.1,3.1,3.4
...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-10 16:00:00,0.1,0.3,0.3,0.3,0.2,0.0,2.1,10.9,2.1,6.2,6.3,5.9
2023-01-10 17:00:00,0.0,0.0,0.0,0.0,0.0,0.0,2.6,6.1,2.6,8.4,6.8,9.6
2023-01-10 18:00:00,0.0,0.0,0.0,0.0,0.0,0.0,4.0,9.7,4.0,17.1,8.8,13.5
2023-01-10 19:00:00,0.0,0.0,0.0,0.0,0.0,0.0,6.6,9.4,6.6,12.3,6.8,11.7
2023-01-10 20:00:00,0.0,0.0,0.1,0.0,0.0,0.0,4.0,7.7,4.0,14.8,8.8,17.0